# Generated by Django 2.2 on 2020-05-09 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200510_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=80)),
                ('address', models.TextField()),
                ('areas_catered', models.TextField()),
                ('description', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=10)),
                ('web_link', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('donation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Donation')),
            ],
        ),
        migrations.CreateModel(
            name='HelpProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prg_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('aid_provided', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='org_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Organization'),
        ),
        migrations.AddField(
            model_name='donation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CustomUser'),
        ),
    ]
