# Generated by Django 2.2 on 2020-05-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200510_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
