# Generated by Django 2.2 on 2020-05-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200510_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='password',
            field=models.CharField(default='abc', max_length=1000),
            preserve_default=False,
        ),
    ]
