# Generated by Django 2.2 on 2020-05-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_organization_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
