# Generated by Django 2.2 on 2020-05-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200510_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpprogram',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='helpprogram',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
