# Generated by Django 2.2 on 2020-05-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200511_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='location',
            field=models.TextField(default='location'),
            preserve_default=False,
        ),
    ]
